### ISSUE TITLE
Crash when player joins multiplayer world

### ISSUE THREAD

**Issue by mcenderdragon** [CyanGenesis/Digimobs-Issues#1]
```
[01:00:17] [Server thread/INFO] [STDOUT]: [digimobs.entities.DigimonStorage:setupStorageDirectory:85]: Creating Digimobs Storage Directory..
[01:00:17] [Server thread/INFO] [STDOUT]: [digimobs.entities.DigimonStorage:setupStorageDirectory:90]: Digimobs Storage Directory found!
[01:00:17] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.EntityJoinWorldEvent@6879c123:
java.lang.NoSuchMethodError: digimobs.handlers.DigimobsEventHandler.adjustSPWorldLevel(Lnet/minecraft/entity/player/EntityPlayer;)V
        at digimobs.handlers.DigimobsEventHandler.onJoinWorldEvent(DigimobsEventHandler.java:105) ~[DigimobsEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_18_DigimobsEventHandler_onJoinWorldEvent_EntityJoinWorldEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
        at net.minecraft.world.World.func_72838_d(World.java:1209) [amu.class:?]
        at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1058) [oo.class:?]
        at net.minecraft.server.management.PlayerList.func_72377_c(PlayerList.java:377) [pl.class:?]
        at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:166) [pl.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:255) [NetworkDispatcher.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72) [NetworkDispatcher.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205) [NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) [gw.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
[01:00:17] [Server thread/ERROR] [FML]: Index: 4 Listeners:
[01:00:17] [Server thread/ERROR] [FML]: 0: HIGHEST
[01:00:17] [Server thread/ERROR] [FML]: 1: ASM: net.minecraftforge.common.ForgeInternalHandler@2ab4b5c5 onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[01:00:17] [Server thread/ERROR] [FML]: 2: NORMAL
[01:00:17] [Server thread/ERROR] [FML]: 3: ASM: digimobs.igwmod.ServerProxy@124c238a onJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[01:00:17] [Server thread/ERROR] [FML]: 4: ASM: digimobs.handlers.DigimobsEventHandler@4e082739 onJoinWorldEvent(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[01:00:17] [Server thread/ERROR] [FML]: 5: ASM: digimobs.obsidianAPI.ObsidianEventHandler@a71df25 onEntityJoin(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[01:00:17] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.NoSuchMethodError: digimobs.handlers.DigimobsEventHandler.adjustSPWorldLevel(Lnet/minecraft/entity/player/EntityPlayer;)V
        at digimobs.handlers.DigimobsEventHandler.onJoinWorldEvent(DigimobsEventHandler.java:105) ~[DigimobsEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_18_DigimobsEventHandler_onJoinWorldEvent_EntityJoinWorldEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
        at net.minecraft.world.World.func_72838_d(World.java:1209) ~[amu.class:?]
        at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1058) ~[oo.class:?]
        at net.minecraft.server.management.PlayerList.func_72377_c(PlayerList.java:377) ~[pl.class:?]
        at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:166) ~[pl.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:255) ~[NetworkDispatcher.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72) ~[NetworkDispatcher.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205) ~[NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) ~[oz.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
[01:00:17] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: C:\Minecraft\Server Digimobs-1.12.2\.\crash-reports\crash-2021-01-09_01.00.17-server.txt
[01:00:17] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[01:00:17] [Server thread/INFO] [minecraft/MinecraftServer]: Saving players
[01:00:17] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
[01:00:17] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'world'/overworld
[01:00:17] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'world'/digimobs
[01:00:18] [Server thread/INFO] [FML]: Unloading dimension 0
[01:00:18] [Server thread/INFO] [FML]: Unloading dimension 8
[01:00:18] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
[01:00:18] [Server Shutdown Thread/INFO] [minecraft/MinecraftServer]: Stopping server
[01:00:18] [Server Shutdown Thread/INFO] [minecraft/MinecraftServer]: Saving players
```

**Comment by CyanGenesis** [comment]
This for an outdated version of the mod, and the solution is also posted in the #faqs section of the discord.

**Comment by mcenderdragon** [comment]
its for the latest 1.12.2 avaiable right now: https://www.curseforge.com/minecraft/mc-mods/digimobs/files/2905805 is there a newer one? And the server coin thingy was the issue according to discord thank you!
