### ISSUE TITLE
Crashing. 

### ISSUE THREAD

**Issue by Aaric90** [CyanGenesis/Digimobs-Issues#39]
**Describe the bug**
Crashing on the Beyond Server. Just trying to make a plot of land. But based on the crash report I'm going to guess its Digimobs side. 

**To Reproduce**
Its trying to spawn an entity. 
Be on dirt.
Use Hoe
Crash.

**Expected behavior**
Not crash, create tilled field

**Crash Report**
`---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 7/11/21 1:23 PM
Description: Rendering entity in world

java.lang.IllegalArgumentException: No enum constant mod.cyan.digimobs.entities.setup.helpers.Mutations.MutationTypes.RAINBOW
	at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_51] {}
	at mod.cyan.digimobs.entities.setup.helpers.Mutations$MutationTypes.valueOf(Mutations.java:12) ~[?:1.16.5-2.0.12] {re:classloading}
	at mod.cyan.digimobs.client.renders.RenderDigimon.getRenderColor(RenderDigimon.java:84) ~[?:1.16.5-2.0.12] {re:classloading}
	at mod.cyan.digimobs.client.renders.RenderDigimon.getRenderColor(RenderDigimon.java:24) ~[?:1.16.5-2.0.12] {re:classloading}
	at software.bernie.digimobs.geckolib3.renderers.geo.GeoEntityRenderer.render(GeoEntityRenderer.java:141) ~[?:1.16.5-2.0.12] {re:classloading}
	at mod.cyan.digimobs.client.renders.RenderDigimon.render(RenderDigimon.java:69) ~[?:1.16.5-2.0.12] {re:classloading}
	at mod.cyan.digimobs.client.renders.RenderDigimon.func_225623_a_(RenderDigimon.java:24) ~[?:1.16.5-2.0.12] {re:classloading}
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:251) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228418_a_(WorldRenderer.java:1202) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1010) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:608) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:425) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.16.jar:36.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$458/1562595588.call(Unknown Source) [forge-1.16.5-36.1.16.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_51] {}
	at mod.cyan.digimobs.entities.setup.helpers.Mutations$MutationTypes.valueOf(Mutations.java:12) ~[?:1.16.5-2.0.12] {re:classloading}
	at mod.cyan.digimobs.client.renders.RenderDigimon.getRenderColor(RenderDigimon.java:84) ~[?:1.16.5-2.0.12] {re:classloading}
	at mod.cyan.digimobs.client.renders.RenderDigimon.getRenderColor(RenderDigimon.java:24) ~[?:1.16.5-2.0.12] {re:classloading}
	at software.bernie.digimobs.geckolib3.renderers.geo.GeoEntityRenderer.render(GeoEntityRenderer.java:141) ~[?:1.16.5-2.0.12] {re:classloading}
	at mod.cyan.digimobs.client.renders.RenderDigimon.render(RenderDigimon.java:69) ~[?:1.16.5-2.0.12] {re:classloading}
	at mod.cyan.digimobs.client.renders.RenderDigimon.func_225623_a_(RenderDigimon.java:24) ~[?:1.16.5-2.0.12] {re:classloading}
-- Entity being rendered --
Details:
	Entity Type: digimobs:agumon (mod.cyan.digimobs.entities.DigimonEntity)
	Entity ID: 1003
	Entity Name: Agumon
	Entity's Exact location: -182.55, 65.00, 0.33
	Entity's Block location: World: (-183,65,0), Chunk: (at 9,4,0 in -12,0; contains blocks -192,0,0 to -177,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.03, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: mod.cyan.digimobs.client.renders.RenderDigimon@6afced93
	Location: -42.47,1.44,45.26 - World: (-43,1,45), Chunk: (at 5,0,13 in -3,2; contains blocks -48,0,32 to -33,255,47), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Rotation: 0.0
	Delta: 0.75999594
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:251) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228418_a_(WorldRenderer.java:1202) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1010) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:608) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}

-- Affected level --
Details:
	All players: 2 total; [ClientPlayerEntity['Aaric90'/1639, l='ClientLevel', x=-140.08, y=61.94, z=-44.93], RemoteClientPlayerEntity['HeartlessSora'/1955, l='ClientLevel', x=-180.58, y=65.00, z=0.15]]
	Chunk stats: Client Chunk Cache: 441, 259
	Level dimension: minecraft:overworld
	Level spawn location: World: (120,64,150), Chunk: (at 8,4,6 in 7,9; contains blocks 112,0,144 to 127,255,159), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 19176986 game time, 1597656 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2029) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.16.jar:36.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$458/1562595588.call(Unknown Source) [forge-1.16.5-36.1.16.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 840821064 bytes (801 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.16.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.16.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.16.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.16.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.16.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.16
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		forge-1.16.5-36.1.16-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |NOSIGNATURE
		Ma-Essentials-1.16.3-3.4.0.jar                    |Ma Essentials                 |maessentials                  |1.16.3-3.4.0        |DONE      |NOSIGNATURE
		backpacked-1.10.1-1.16.3.jar                      |Backpacked                    |backpacked                    |1.10.1              |DONE      |NOSIGNATURE
		backpacker-1.3.1-1.16.3.jar                       |Backpacker                    |backpacker                    |1.3.1               |DONE      |NOSIGNATURE
		forge-1.16.5-36.1.16-universal.jar                |Forge                         |forge                         |36.1.16             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		digimobs-1.16.5-2.0.12.jar                        |Digimobs                      |digimobs                      |1.16.5-2.0.12       |DONE      |NOSIGNATURE
		cfm-7.0.0pre22-1.16.3.jar                         |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre22         |DONE      |NOSIGNATURE
		CalemiUtils-1.16.4-1.1.1.jar                      |Calemi's Utils                |calemiutils                   |1.1.1               |DONE      |NOSIGNATURE
		architectury-1.18.25-forge.jar                    |Architectury                  |architectury                  |1.18.25             |DONE      |NOSIGNATURE
		ftb-gui-library-1605.2.1.41-forge.jar             |FTB GUI Library               |ftbguilibrary                 |1605.2.1.41         |DONE      |NOSIGNATURE
		ftb-chunks-1605.2.3-build.75.jar                  |FTB Chunks                    |ftbchunks                     |1605.2.3-build.75   |DONE      |NOSIGNATURE
	Crash Report UUID: 2aab8f9e-fd7e-4bf2-88de-d06fc7dd303c
	Launched Version: 1.16.5-forge-36.1.16
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1080/PCIe/SSE2 GL version 4.6.0 NVIDIA 465.89, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz`

**Versions**
 Minecraft Version - 1.16.5
 Forge Version 36.1.16
 Digimobs Version - 2.0.12

**Additional context**

**Comment by Aaric90** [comment]
Sora placed a redagumon on the server. closing...
