### ISSUE TITLE
Game crashes when looking at my Phoenixmon's stats

### ISSUE THREAD

**Issue by Kawaiitron** [CyanGenesis/Digimobs-Issues#6]
No idea what any of this means. I don't speak crash logs, but hopefully you can figure this out. If it helps, I did modify the Digi with NBTedit, but I don't think I did anything wrong. I set its level to I think 100, along with all of its stats being set to 100. Can't remember what I set the age to. I didn't touch any other values, though.

---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 1/23/21 1:43 PM
Description: Rendering screen

java.lang.ArrayIndexOutOfBoundsException: 100
	at mod.cyan.digimobs.entities.Stats.getNeededExp(Stats.java:195) ~[?:1.15.2-2.0.3] {re:classloading}
	at mod.cyan.digimobs.client.gui.DigimonStatsScreen.render(DigimonStatsScreen.java:138) ~[?:1.15.2-2.0.3] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:480) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:924) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.15.2-31.2.46.jar:31.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$415/687501326.call(Unknown Source) [forge-1.15.2-31.2.46.jar:31.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at mod.cyan.digimobs.entities.Stats.getNeededExp(Stats.java:195)
	at mod.cyan.digimobs.client.gui.DigimonStatsScreen.render(DigimonStatsScreen.java:138)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)

-- Screen render details --
Details:
	Screen name: mod.cyan.digimobs.client.gui.DigimonStatsScreen
	Mouse location: Scaled: (247, 72). Absolute: (991.000000, 289.000000)
	Screen size: Scaled: (480, 255). Absolute: (1920, 1017). Scale factor of 4.000000

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Kawaiitron'/57, l='MpServer', x=-307.31, y=76.00, z=-310.09]]
	Chunk stats: Client Chunk Cache: 841, 538
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: -4963906099643141942
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (38,63,-96), Chunk: (at 6,3,0 in 2,-6; contains blocks 32,0,-96 to 47,255,-81), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 142894 game time, 142894 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:442)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1763)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:567)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$415/687501326.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1297231832 bytes (1237 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.1.2+70+master.2845bb9
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-2.2.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.46.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.46.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.46.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.46.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.2.46.jar fml TRANSFORMATIONSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.46
	FML Language Providers: 
		javafml@31.2
		minecraft@1
	Mod List: 
		forge-1.15.2-31.2.46-client.jar Minecraft {minecraft@1.15.2 DONE}
		forge-1.15.2-31.2.46-universal.jar Forge {forge@31.2.46 DONE}
		digimobs-1.15.2-2.0.3.jar Digimobs {digimobs@1.15.2-2.0.3 DONE, nbtedit@0.9.0 DONE}
	Launched Version: 1.15.2-forge-31.2.46
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1070/PCIe/SSE2 GL version 4.5.0 NVIDIA 385.54, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-7820HK CPU @ 2.90GHz

**Comment by CyanGenesis** [comment]
It's a good idea to follow the template when posting a crash report..But it looks like there is an issue with the digimon attempting to calculate exp when at max level. I'll look into it.

**Comment by CyanGenesis** [comment]
Applied some checks that should now stop calculating exp at max level. Should be fixed for next update, along with everywhere else the exp calculation kicks in.
