### ISSUE TITLE
Ticking Entity Crash

### ISSUE THREAD

**Issue by BoredRecluse** [CyanGenesis/Digimobs-Issues#68]
After a bit of time passes, especially while in LAN or another multiplayer mod, like the Essentials mod, the game would crash giving a crash report of a ticking entity.  At one point it was a yuramon, but this is not always the case.

Here is the Crash Report:

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 8/2/22 9:24 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at mod.cyan.digimobs.entities.DigimonEntity.doSpecial(DigimonEntity.java:875) ~[?:1.16.5-2.1.9a] {re:classloading}
	at mod.cyan.digimobs.entities.DigimonAttackGoal.checkAndPerformSpecialAttack(DigimonAttackGoal.java:145) ~[?:1.16.5-2.1.9a] {re:classloading}
	at mod.cyan.digimobs.entities.DigimonAttackGoal.checkForTypeOfAttack(DigimonAttackGoal.java:116) ~[?:1.16.5-2.1.9a] {re:classloading}
	at mod.cyan.digimobs.entities.DigimonAttackGoal.func_75246_d(DigimonAttackGoal.java:103) ~[?:1.16.5-2.1.9a] {re:classloading}
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55) ~[?:?] {re:classloading}
	at com.performant.coremod.entity.ai.CustomGoalSelector.func_75774_a(CustomGoalSelector.java:392) ~[?:1.16.2-5-3.99m] {re:classloading}
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:682) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:entity.MobEntityDespawnMixin,pl:mixin:APP:performant.mixins.json:entity.MobEntityMixin,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2413) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:entity.LivingEntityMixin,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:488) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:entity.MobEntityDespawnMixin,pl:mixin:APP:performant.mixins.json:entity.MobEntityMixin,pl:mixin:A}
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:127) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.entity.passive.AnimalEntity.func_70636_d(AnimalEntity.java:51) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2160) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:entity.LivingEntityMixin,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:entity.MobEntityDespawnMixin,pl:mixin:APP:performant.mixins.json:entity.MobEntityMixin,pl:mixin:A}
	at mod.cyan.digimobs.entities.DigimonEntity.func_70071_h_(DigimonEntity.java:215) ~[?:1.16.5-2.1.9a] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:performant.mixins.json:world.ServerWorldBlockUpdateMixin,pl:mixin:APP:performant.mixins.json:world.ServerWorldMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld$$Lambda$8912/1568083258.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:performant.mixins.json:world.ServerWorldBlockUpdateMixin,pl:mixin:APP:performant.mixins.json:world.ServerWorldMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.essential.json:server.Mixin_PublishServerStatusResponse,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.essential.json:server.Mixin_PublishServerStatusResponse,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:mixins.essential.json:server.integrated.MixinIntegratedServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.essential.json:server.Mixin_PublishServerStatusResponse,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.essential.json:server.Mixin_PublishServerStatusResponse,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$8580/1921560536.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at mod.cyan.digimobs.entities.DigimonEntity.doSpecial(DigimonEntity.java:875) ~[?:1.16.5-2.1.9a] {re:classloading}
	at mod.cyan.digimobs.entities.DigimonAttackGoal.checkAndPerformSpecialAttack(DigimonAttackGoal.java:145) ~[?:1.16.5-2.1.9a] {re:classloading}
	at mod.cyan.digimobs.entities.DigimonAttackGoal.checkForTypeOfAttack(DigimonAttackGoal.java:116) ~[?:1.16.5-2.1.9a] {re:classloading}
	at mod.cyan.digimobs.entities.DigimonAttackGoal.func_75246_d(DigimonAttackGoal.java:103) ~[?:1.16.5-2.1.9a] {re:classloading}
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55) ~[?:?] {re:classloading}
	at com.performant.coremod.entity.ai.CustomGoalSelector.func_75774_a(CustomGoalSelector.java:392) ~[?:1.16.2-5-3.99m] {re:classloading}
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:682) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:entity.MobEntityDespawnMixin,pl:mixin:APP:performant.mixins.json:entity.MobEntityMixin,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2413) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:entity.LivingEntityMixin,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:488) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:entity.MobEntityDespawnMixin,pl:mixin:APP:performant.mixins.json:entity.MobEntityMixin,pl:mixin:A}
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:127) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.entity.passive.AnimalEntity.func_70636_d(AnimalEntity.java:51) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2160) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:entity.LivingEntityMixin,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:entity.MobEntityDespawnMixin,pl:mixin:APP:performant.mixins.json:entity.MobEntityMixin,pl:mixin:A}
	at mod.cyan.digimobs.entities.DigimonEntity.func_70071_h_(DigimonEntity.java:215) ~[?:1.16.5-2.1.9a] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:performant.mixins.json:world.ServerWorldBlockUpdateMixin,pl:mixin:APP:performant.mixins.json:world.ServerWorldMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld$$Lambda$8912/1568083258.accept(Unknown Source) ~[?:?] {}
-- Entity being ticked --
Details:
	Entity Type: digimobs:yuramon (mod.cyan.digimobs.entities.DigimonEntity)
	Entity ID: 42515
	Entity Name: Yuramon
	Entity's Exact location: 35.20, 71.00, 51.20
	Entity's Block location: World: (35,71,51), Chunk: (at 3,4,3 in 2,3; contains blocks 32,0,48 to 47,255,63), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.02, -0.08, 0.02
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:performant.mixins.json:world.ServerWorldBlockUpdateMixin,pl:mixin:APP:performant.mixins.json:world.ServerWorldMixin,pl:mixin:A}

-- Affected level --
Details:
	All players: 2 total; [ServerPlayerEntity['BoredRecluse'/235, l='ServerLevel[Survive!]', x=22.30, y=71.00, z=18.94], ServerPlayerEntity['AgentBlueIsTaken'/43245, l='ServerLevel[Survive!]', x=83.71, y=72.00, z=26.17]]
	Chunk stats: ServerChunkCache: 2197
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,68,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 32710 game time, 32710 day time
	Level name: Survive!
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 86237 (now: false), thunder time: 107119 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.essential.json:server.Mixin_PublishServerStatusResponse,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.essential.json:server.Mixin_PublishServerStatusResponse,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:mixins.essential.json:server.integrated.MixinIntegratedServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.essential.json:server.Mixin_PublishServerStatusResponse,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.essential.json:server.Mixin_PublishServerStatusResponse,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$8580/1921560536.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 449903536 bytes (429 MB) / 2686451712 bytes (2562 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 20
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/Essential-forge_1-16-5.jar essential-loader TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.34.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.34
	FML Language Providers: 
		javafml@36.2
		minecraft@1
		kotlinforforge@1.17.0
	Mod List: 
		forge-1.16.5-36.2.34-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		performant-1.16.2-5-3.99m.jar                     |Performant                    |performant                    |3.73m               |DONE      |Manifest: NOSIGNATURE
		JustEnoughResources-1.16.5-0.12.1.128.jar         |Just Enough Resources         |jeresources                   |0.12.1.128          |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.34-universal.jar                |Forge                         |forge                         |36.2.34             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Waystones_1.16.5-7.6.4.jar                        |Waystones                     |waystones                     |7.6.4               |DONE      |Manifest: NOSIGNATURE
		JJBA-RipplesOfThePast-1.16.5-0.2.0.1.jar          |Ripples of the Past           |jojo                          |0.2.0.1             |DONE      |Manifest: NOSIGNATURE
		ExplorersCompass-1.16.5-1.1.2-forge.jar           |Explorer's Compass            |explorerscompass              |1.16.5-1.1.2-forge  |DONE      |Manifest: NOSIGNATURE
		digimobs-1.16.5-2.1.9a.jar                        |Digimobs                      |digimobs                      |1.16.5-2.1.9a       |DONE      |Manifest: NOSIGNATURE
		Clumps-6.0.0.28.jar                               |Clumps                        |clumps                        |6.0.0.28            |DONE      |Manifest: NOSIGNATURE
		journeymap-1.16.5-5.8.5p5.jar                     |Journeymap                    |journeymap                    |5.8.5p5             |DONE      |Manifest: NOSIGNATURE
		Essential (forge_1.16.5).jar                      |Essential                     |essential                     |4383+g232c05c73     |DONE      |Manifest: NOSIGNATURE
		NaturesCompass-1.16.5-1.9.1-forge.jar             |Nature's Compass              |naturescompass                |1.16.5-1.9.1-forge  |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.152.jar                          |Just Enough Items             |jei                           |7.7.1.152           |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 0b86711d-c25d-4c56-b31c-dd42f02aa1c6
	Player Count: 2 / 8; [ServerPlayerEntity['BoredRecluse'/235, l='ServerLevel[Survive!]', x=22.30, y=71.00, z=18.94], ServerPlayerEntity['AgentBlueIsTaken'/43245, l='ServerLevel[Survive!]', x=83.71, y=72.00, z=26.17]]
	Data Packs: vanilla, mod:performant (incompatible), mod:jeresources, mod:forge, mod:waystones (incompatible), mod:jojo, mod:explorerscompass, mod:digimobs, mod:clumps, mod:journeymap (incompatible), mod:essential, mod:naturescompass (incompatible), mod:jei
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by CyanGenesis** [comment]
This is an incompatibility with Performant, you’ll have to remove it. For some reason it does not like edited AI.
